### ISSUE TITLE
请问time points在这里已经完全打散了吗？

### ISSUE THREAD

**Issue by x2x5** [xujiayang530/DGCNN#6]
我原来的理解是，测试的时候，每个eeg是一个 CxT的数据，如果用DE特征，应该是CxTx5的数据，但是从代码调试来看，测试和的时候，变成每个样本就是一个Cx5的数据，也就是说，对eeg分类变成了对单个时间步分类吗？我不太懂这里的设置，不知道是不是我想的这样？谢谢~ 另外您的代码写的非常的好，帮助太大了 ~

**Comment by xujiayang530** [comment]
每个eeg会分段，在每一个小段计算de，一个小段就是一个样本，每个样本有C X 5维度的特征

**Comment by x2x5** [comment]
> 每个eeg会分段，在每一个小段计算de，一个小段就是一个样本，每个样本有C X 5维度的特征

了解了，感谢~
